### ISSUE TITLE
Not working on 2025.09

### ISSUE THREAD

**Issue by CMGeorge** [CMGeorge/homeassistant_sabiana_smart_energy#5]
## Version of the custom_component
1.0.0

## Configuration

```yaml

Această eroare originează într-o integrare non-standard.

Logger: custom_components.sabiana_energy_smart.modbus_client
Sursa: custom_components/sabiana_energy_smart/modbus_client.py:54
integrare: Sabiana Energy Smart (documentația, probleme)
Prima dată când a avut loc: 11:17:48 (160623 occurrences)
Ultima înregistrare: 12:56:57

Unexpected error reading 0x0302: ModbusClientMixin.read_holding_registers() got an unexpected keyword argument 'slave'
Unexpected error reading 0x0303: ModbusClientMixin.read_holding_registers() got an unexpected keyword argument 'slave'
Unexpected error reading 0x0304: ModbusClientMixin.read_holding_registers() got an unexpected keyword argument 'slave'
Unexpected error reading 0x0305: ModbusClientMixin.read_holding_registers() got an unexpected keyword argument 'slave'
Unexpected error reading 0x0117: ModbusClientMixin.read_holding_registers() got an unexpected keyword argument 'slave'


```

## Debug log

```text

Add your logs here.

```
